#pragma config(Motor,  port2,           rfWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lfWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rbWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lbWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           w1Arm,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           w2Arm,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           w3Arm,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           w4Arm,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rkCompetition.h"

void init() { }

task auton() { }

task userOp() {
	while(true) {
		motor[lfWheel] = motor[lbWheel] = vexRT[Ch3] + vexRT[Ch1];
		motor[rfWheel] = motor[rbWheel] = vexRT[Ch3] - vexRT[Ch1];

//		motor[rfWheel] = (vexRT[Ch3] - vexRT[Ch1]);
//		motor[lfWheel] = (vexRT[Ch3] + vexRT[Ch1]);
//		motor[rbWheel] = (vexRT[Ch1] - vexRT[Ch3]);
//		motor[lbWheel] = (vexRT[Ch1] + vexRT[Ch3]);

		if(vexRT[Btn5U] == 1 || vexRT[Btn6U] == 1) {
			motor[w1Arm] = 127;
			motor[w2Arm] = 127;
			motor[w3Arm] = 127;
			motor[w4Arm] = 127;
		}
		else if(vexRT[Btn5D] == 1 || vexRT[Btn6D] == 1) {
			motor[w1Arm] = -127;
			motor[w2Arm] = -127;
			motor[w3Arm] = -127;
			motor[w4Arm] = -127;
		}
		else {
			motor[w1Arm] = 0;
			motor[w2Arm] = 0;
			motor[w3Arm] = 0;
			motor[w4Arm] = 0;
		}
	}
}

void endAuton() { }
void endUserOp() { }
