#pragma config(Motor,  port2,           frWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           brWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           blWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           flWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           blLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           tlLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           trLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           brLift,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void holoSteer(int fb, int strafe, int rot) { //fb = forward/back motion
	motor[flWheel] = fb + strafe + rot;
	motor[blWheel] = fb - strafe + rot;
	motor[brWheel] = -(fb + strafe - rot);
	motor[frWheel] = -(fb - strafe - rot);
}

int liftCtl(int pwr) {
	motor[tlLift] =
		motor[brLift] =
		pwr;
	motor[trLift] =
		motor[blLift] =
		-pwr;
	return pwr;
}

int liftPwr() {
	if(vexRT[Btn5U] ^ vexRT[Btn5D] ^ vexRT[Btn6U] ^ vexRT[Btn6D]) {
		if(vexRT[Btn5U])
			return 63;
		else if(vexRT[Btn5D])
			return -63;
		else if(vexRT[Btn6U])
			return 127;
		else
			return -127;
	}

	else
		return 0;
}

task main() {
	int rx,
		ly,
		lx;

	while(true) {
		rx = (abs(vexRT[Ch1]) >= 7) ? vexRT[Ch1] : 0;
		ly = (abs(vexRT[Ch3]) >= 7) ? vexRT[Ch3] : 0;
		lx = (abs(vexRT[Ch4]) >= 7) ? vexRT[Ch4] : 0;

		holoSteer(ly, lx, rx);

		liftCtl(liftPwr());
	}
}
