#pragma config(Motor,  port1,           lfWheel,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           lbWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           aMotor,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           bMotor,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           cMotor,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           dMotor,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rbWheel,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rfWheel,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void standard(int pwrA, int pwrB, int s) {
	motor[lfWheel] = motor[lbWheel] = pwrA;
	motor[rfWheel] = motor[rbWheel] = pwrB;
	wait1Msec(s);
}
void arm(int pwr, int s) {
	motor[aMotor] = motor[bMotor] = motor[cMotor] = motor[dMotor] = pwr;
	wait1Msec(s);
}


task main()
{
	motor[lClaw] = -127;
	motor[rClaw] = -127;
	wait1Msec(300);
	motor[lClaw] = 0;
	motor[rClaw] = 0;
	wait1Msec(200);
	arm(127, 200);
	arm(0, 350);
	arm(-127, 100);
	arm(0, 350);
	standard(127, 127, 1500);
	standard(0, 0, 350);
	motor[lClaw] = 127;
	motor[rClaw] = 127;
	wait1Msec(750);
	motor[lClaw] = 0;
	motor[rClaw] = 0;
	wait1Msec(300);
	standard(-127, -70, 500);
	standard(0, 0, 200);
	standard(-127, 127, 345);
	standard(0, 0, 200);
	


}
