#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    peBatt,         sensorAnalog)
#pragma config(Sensor, in2,    rLine,          sensorLineFollower)
#pragma config(Sensor, in3,    mLine,          sensorLineFollower)
#pragma config(Sensor, in4,    lLine,          sensorLineFollower)
#pragma config(Sensor, dgtl1,  lClawPn,        sensorDigitalOut)
#pragma config(Sensor, dgtl2,  rClawPn,        sensorDigitalOut)
#pragma config(Sensor, dgtl3,  lDriveEnc,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rDriveEnc,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  liftEnc,        sensorQuadEncoder)
#pragma config(Motor,  port1,           frWheel,       tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           brWheel,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           trLift,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           mrLift,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           brLift,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           tlLift,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mlLift,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           blLift,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           blWheel,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          flWheel,       tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define setDriveR(pwr) motor[frWheel] = \
	motor[brWheel] = \
	pwr

#define setDriveL(pwr) motor[flWheel] = \
	motor[blWheel] = \
	pwr

#define setLift(pwr) motor[tlLift] = \
	motor[mlLift] = \
	motor[blLift] = \
	motor[trLift] = \
	motor[mrLift] = \
	motor[brLift] = \
	pwr


#define setClaw(pwr) SensorValue[lClawPn] = \
	SensorValue[rClawPn] = \
	pwr

void setDrive(int lPwr, int rPwr) {
	setDriveL(lPwr);
	setDriveR(rPwr);
	return;
}


typedef struct {
	bool val,
		valLast,
		delta,
		rise,
		fall;
} Toggle;

bool upTog(Toggle* tog, bool val) {
	tog->valLast = tog->val;
	tog->val = val;
	tog->delta = ((tog->val && !tog->valLast) || (!tog->val && tog->valLast)); //I don't like bad type warnings, so this is a manual xor
	tog->rise = tog->delta && tog->val;
	tog->fall = tog->delta && tog->valLast;
	return tog->val;
}

bool togVal(Toggle* tog) {
	return tog->val;
}

bool togValLast(Toggle* tog) {
	return tog->valLast;
}

bool togDelta(Toggle* tog) {
	return tog->delta;
}

bool togRising(Toggle* tog) {
	return tog->rise;
}

bool falling(Toggle* tog) {
	return tog->fall;
}



typedef struct {
	int target,
		val,
		valLast,
		err,
		mtrPwr;
	float prop,
		integ,
		integLim,
		deriv,
		kP,
		kI,
		kD;
} Pid;

void initPid(Pid* pid, float integLim, float kP, float kI, float kD) {
	pid->val =
		pid->valLast =
		pid->integ =
		pid->mtrPwr =
		0;
	pid->integLim = integLim;
	pid->kP = kP;
	pid->kI = kI;
	pid->kD = kD;
}

int setPidTarg(Pid* pid, int targ) {
	pid->target = targ;
	pid->integ = 0;
	return pid->target;
}

int upPid(Pid* pid, int val, int dt) {
	pid->val = val;
	pid->err = pid->target - pid->val; //Calculate error
	pid->prop = pid->err * pid->kP;  //Calculate proportional
	pid->integ += (pid->err * pid->kI) * dt; //Calculate integral
	if(fabs(pid->integ) > pid->integLim) //Collar integral
		pid->integ = pid->integLim * sgn(pid->integ);
	pid->deriv = pid->kD * (pid->val - pid->valLast) / dt; //Calculate derivative
	pid->mtrPwr = round(pid->prop + pid->integ + pid->deriv); //Calculate motor power
	return pid->mtrPwr;
}

int getPidPwr(Pid* pid) {
	return pid->mtrPwr;
}

task battLvls() {
	float battLvls[3] = { 0, 0, 0 };
	string battString[2];
	string* pBattString[2];

	for(int i = 0; i < 2; i++)
		pBattString[i] = &battString[i];

	for(int i = 0; i < 3; i++)
		battLvls[i] = 0;

	while(true) {

		for(int i = 0; i < 3; i++)
			battLvls[i] = 0;

		for(int i = 0; i < 10; i++) {
			battLvls[0] += nImmediateBatteryLevel / 10000.;
			battLvls[1] += SensorValue[in1] / 456.;
			battLvls[2] += BackupBatteryLevel / 10000.;
			wait1Msec(20);
		}

		sprintf(*pBattString[0], "%2.2fV || %2.2fV", battLvls[0], battLvls[1]);
		sprintf(*pBattString[1], "%2.2fV", battLvls[2]);

		displayLCDCenteredString(0, *pBattString[0]);
		displayLCDCenteredString(1, *pBattString[1]);

		wait1Msec(20);

	}
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

Toggle LiftTog;

Pid LiftPid,
	DrivePidL,
	DrivePidR;

void pre_auton()
{
  //autonCt = lcdAuton();
  startTask(battLvls);

  initPid(&LiftPid, 127, .1, .001, .01);
  initPid(&DrivePidR, 127, .1, .001, .01);
  initPid(&DrivePidL, 127, .1, .001, .01);

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  //switch(autonCt) {
  //	case 1:
  //		redPoleAuton();
  //		break;
  //	case 2:
  //		bluePoleAuton();
  //		break;
  //	case 3:
  //		redCubeAuton();
  //		break;
  //	case 4:
  //		blueCubeAuton();
  //		break;
  //}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol() {
  int timeLast,
  	time,
  	dt,
  	sticks[4] = { 0, 0, 0, 0 };


	startTask(battLvls);

	while(true) {
		timeLast = time;
		time = nSysTime;
		dt = time - timeLast;
		upPid(&LiftPid, SensorValue[liftEnc], dt);

		upTog(&LiftTog, (vexRT[Btn5U] ^ vexRT[Btn5D]));

		for(int i = 0; i < 4; i++)
			sticks[i] = (fabs(vexRT[i]) > 7)
				? vexRT[i]
				: 0;

		setDrive(sticks[2] + sticks[0], sticks[2] - sticks[0]);

		if(falling(&LiftTog))
			setPidTarg(&LiftPid, SensorValue[liftEnc]);

		if(togVal(&LiftTog)) {
			if(vexRT[Btn5U])
				setLift(127);
			else
				setLift(-127);
		}
		
		else
			setLift(getPidPwr(&LiftPid));

		if(vexRT[Btn6U] ^ vexRT[Btn6D]) {
			if(vexRT[Btn6U])
				setClaw(true);
			else
				setClaw(false);
		}

		wait1Msec(20);

	}
}
